### PR TITLE
added matches for incredible performance gain

### PR DESCRIPTION
**Pull request by Stunkymonkey**
if have added 2 matches
and now its faster, than imagined
i would like to have this one merged

Greetings Stunkymonkey

### CODE REVIEW

**Comment by arigit** [comment]
Thank you for this! pretty amazing how effective this changes is.

There was a conflict to get this merged though, plus run into an odd situation with one server that sometimes aborts during Suspend so multiple suspends can show one after another. And it also exhibits more than one wakeup in a sequence.

So I'm doing some surgery in the logic to handle this use case. Will post back once solved and merge everything.

Here's the problem.

[Analyzing Journal] ...|2016-11-25 03:10:06.590920 Suspending system...
2016-11-25 08:45:54.245125 PM: Finishing wakeup.
2016-11-25 20:25:11.451280 PM: Finishing wakeup.
2016-11-25 20:25:11.464173 Suspending system...
2016-11-26 01:48:45.242596 PM: Finishing wakeup.
2016-11-26 01:48:45.246282 Suspending system...
2016-11-26 02:25:07.134693 Suspending system...
2016-11-26 09:27:00.251301 PM: Finishing wakeup.
2016-11-26 12:52:44.417673 Suspending system...
2016-11-26 14:37:46.331019 PM: Finishing wakeup.
2016-11-26 15:16:57.168063 Suspending system...
2016-11-26 20:28:53.329037 PM: Finishing wakeup.
2016-11-27 01:57:04.365355 Suspending system...
2016-11-27 08:57:00.243710 PM: Finishing wakeup.
     Wake Timestamp     |    Suspend Timestamp   |       Awake Time       |
  --------------------  |  --------------------  |  --------------------  |
(datetime.datetime(2016, 11, 24, 22, 41, 30, 93089), datetime.datetime(2016, 11, 25, 3, 10, 6, 590920))
calcTimeDif: 2016-11-25 03:10:06.590920 2016-11-24 22:41:30.093089
(datetime.datetime(2016, 11, 25, 20, 25, 11, 451280), datetime.datetime(2016, 11, 25, 20, 25, 11, 464173))
calcTimeDif: 2016-11-25 20:25:11.464173 2016-11-25 20:25:11.451280
(datetime.datetime(2016, 11, 26, 1, 48, 45, 242596), datetime.datetime(2016, 11, 26, 1, 48, 45, 246282))
calcTimeDif: 2016-11-26 01:48:45.246282 2016-11-26 01:48:45.242596
(None, datetime.datetime(2016, 11, 26, 2, 25, 7, 134693))
calcTimeDif: 2016-11-26 02:25:07.134693 None
Traceback (most recent call last):
  File "lastwake.py", line 142, in <module>
    awakeTime = calculateTimeDiference(i[1], i[0])
  File "lastwake.py", line 69, in calculateTimeDiference
    awakeSeconds = (suspendTime - awakeTime).total_seconds()
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'



It doesn't fail in a normal desktop use case:

Initial Boot Timestamp:  2016-11-20 11:17:41 

[Analyzing Journal] ...|2016-11-20 18:26:26.681696 Suspending system...
2016-11-20 20:48:01.809111 PM: Finishing wakeup.
2016-11-20 21:11:32.129828 Suspending system...
2016-11-21 01:05:49.792400 PM: Finishing wakeup.
2016-11-21 02:41:16.416129 Suspending system...
2016-11-22 01:29:16.815376 PM: Finishing wakeup.
2016-11-22 03:14:43.997883 Suspending system...
2016-11-24 00:24:49.393802 PM: Finishing wakeup.
2016-11-24 02:04:00.140766 Suspending system...
2016-11-25 00:20:51.391568 PM: Finishing wakeup.
2016-11-25 02:37:10.901466 Suspending system...
2016-11-27 01:58:11.837509 PM: Finishing wakeup.
     Wake Timestamp     |    Suspend Timestamp   |       Awake Time       |
  --------------------  |  --------------------  |  --------------------  |
(datetime.datetime(2016, 11, 20, 11, 17, 41, 473432), datetime.datetime(2016, 11, 20, 18, 26, 26, 681696))
(datetime.datetime(2016, 11, 20, 20, 48, 1, 809111), datetime.datetime(2016, 11, 20, 21, 11, 32, 129828))
(datetime.datetime(2016, 11, 21, 1, 5, 49, 792400), datetime.datetime(2016, 11, 21, 2, 41, 16, 416129))
(datetime.datetime(2016, 11, 22, 1, 29, 16, 815376), datetime.datetime(2016, 11, 22, 3, 14, 43, 997883))
(datetime.datetime(2016, 11, 24, 0, 24, 49, 393802), datetime.datetime(2016, 11, 24, 2, 4, 0, 140766))
(datetime.datetime(2016, 11, 25, 0, 20, 51, 391568), datetime.datetime(2016, 11, 25, 2, 37, 10, 901466))
(datetime.datetime(2016, 11, 27, 1, 58, 11, 837509), datetime.datetime(2016, 11, 27, 12, 31, 48, 908528))
   2016-11-20 11:17:41  |   2016-11-20 18:26:26  |          7h  8m        |
   2016-11-20 20:48:01  |   2016-11-20 21:11:32  |          0h 23m        |
   2016-11-21 01:05:49  |   2016-11-21 02:41:16  |          1h 35m        |
   2016-11-22 01:29:16  |   2016-11-22 03:14:43  |          1h 45m        |
   2016-11-24 00:24:49  |   2016-11-24 02:04:00  |          1h 39m        |
   2016-11-25 00:20:51  |   2016-11-25 02:37:10  |          2h 16m        |
   2016-11-27 01:58:11  |      (Still Awake)     |         10h 33m        |
  --------------------  |  --------------------  |  --------------------  | 

Summary: Days Since Boot [7.05] | Days Awake [1.06] | Suspend/Wake Cycles: [6]

**Comment by Stunkymonkey** [comment]
is the normal lastwake-script working in your server?

**Comment by arigit** [comment]
Nope, it was broken before this last optimization. For sure this optimization is not related to the breakage.

Maybe lastwake  could never manage the this use case, I'm not not sure anymore :)
I'll add logic so it can handle repeated Suspends and repeated Wakeups gracefully. 

I know the cause for the repeated suspends, I have some suspend-hooks in the server  that can abort the suspend under certain conditions. I am not clear on why the repeated wakeup messages happen though, but anyways it's clear that they happen so lastwake needs to handle the case.

In the code that inspects the entries, I will add a flag and make it look for a "last repeated suspend" first, then switch and look for the "first wakeup" and ignore repetitions of either

**Comment by arigit** [comment]
I think I fixed it.

I will merge manually your changes of this pull request, plus the new logic. The results it gives are aligned with true awake times even in the server with the log output as above.

Please take a look at master in a couple of minutes and give it a try if you can. One corner case I would like to test is running the script right after a cold boot before any suspend happens. I think it should work OK but would be good to double check

**Pull request closed without merging**
